config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'best50m_results/index'
  devise_for :users, class_name: 'GogglesDb::User',
                     controllers: {
                       sessions: 'users/sessions'
                     }
  root to: 'home#index'

  # Mounting and usage of the Engine:
  mount GogglesDb::Engine => '/'

  get 'home/index'
  get 'home/latest_updates'

  get 'best_results/best_50m', to: 'best_results#best_50m', as: 'best_50m_results'
  get 'best_results/best_50_and_100', to: 'best_results#best_50_and_100', as: 'best_50_and_100_results'
  get 'best_results/best_50_and_100_5y', to: 'best_results#best_50_and_100_5y', as: 'best_50_and_100_5y_results'
  get 'best_results/best_in_3y', to: 'best_results#best_in_3y', as: 'best_in_3y_results'
  get 'best_results/best_in_5y', to: 'best_results#best_in_5y', as: 'best_in_5y_results'
  get 'best_results/all_time_best', to: 'best_results#all_time_best', as: 'all_time_best_results'

  get 'pull/index'
  get 'pull/calendar_files'
  get 'pull/result_files'
  put 'pull/result_files', to: 'pull#result_files', as: 'update_result_files'

  post 'pull/run_crawler_api', to: 'pull#run_crawler_api', as: 'run_crawler_api'
  get 'pull/edit_name'
  get 'pull/edit_file'
  put 'pull/file_rename'
  put 'pull/file_edit'
  delete 'pull/file_delete'
  post 'pull/process_calendar_file', to: 'pull#process_calendar_file', as: 'process_calendar_file'

  get 'pdf/extract_txt', to: 'pdf#extract_txt', as: 'pdf_extract_txt'
  put 'pdf/scan'
  put 'pdf/log_contents'

  get 'data_fix/commit_phase6_report'
  get 'data_fix/review_sessions', to: 'data_fix#review_sessions', as: 'review_sessions'
  get 'data_fix/review_teams', to: 'data_fix#review_teams', as: 'review_teams'
  get 'data_fix/review_swimmers', to: 'data_fix#review_swimmers', as: 'review_swimmers'
  get 'data_fix/review_events', to: 'data_fix#review_events', as: 'review_events'
  get 'data_fix/review_results', to: 'data_fix#review_results', as: 'review_results'
  get 'data_fix/results_chunk_v2', to: 'data_fix#results_chunk_v2', as: 'results_chunk_v2'
  post 'data_fix/commit_phase6', to: 'data_fix#commit_phase6', as: 'commit_phase6'
  patch 'data_fix/update_phase1_meeting', to: 'data_fix#update_phase1_meeting', as: 'update_phase1_meeting'
  patch 'data_fix/update_phase1_session', to: 'data_fix#update_phase1_session', as: 'update_phase1_session'
  post 'data_fix/add_session', to: 'data_fix#add_session', as: 'data_fix_add_session'
  delete 'data_fix/delete_session', to: 'data_fix#delete_session', as: 'data_fix_delete_session'
  post 'data_fix/rescan_phase1_sessions', to: 'data_fix#rescan_phase1_sessions', as: 'rescan_phase1_sessions'
  patch 'data_fix/update_phase2_team', to: 'data_fix#update_phase2_team', as: 'update_phase2_team'
  post 'data_fix/add_team', to: 'data_fix#add_team', as: 'data_fix_add_team'
  delete 'data_fix/delete_team', to: 'data_fix#delete_team', as: 'data_fix_delete_team'
  patch 'data_fix/update_phase3_swimmer', to: 'data_fix#update_phase3_swimmer', as: 'update_phase3_swimmer'
  post 'data_fix/add_swimmer', to: 'data_fix#add_swimmer', as: 'data_fix_add_swimmer'
  delete 'data_fix/delete_swimmer', to: 'data_fix#delete_swimmer', as: 'data_fix_delete_swimmer'
  post 'data_fix/merge_phase3_swimmers', to: 'data_fix#merge_phase3_swimmers', as: 'merge_phase3_swimmers'
  patch 'data_fix/update_phase4_event', to: 'data_fix#update_phase4_event', as: 'update_phase4_event'
  post 'data_fix/add_event', to: 'data_fix#add_event', as: 'data_fix_add_event'
  delete 'data_fix/delete_event', to: 'data_fix#delete_event', as: 'data_fix_delete_event'
  patch 'data_fix/update', to: 'data_fix#update', as: 'data_fix_update'
  get 'data_fix/coded_name', to: 'data_fix#coded_name'
  get 'data_fix/teams_for_swimmer/:swimmer_id', to: 'data_fix#teams_for_swimmer', as: 'data_fix_teams_for_swimmer'
  delete 'data_fix/purge', to: 'data_fix#purge', as: 'data_fix_purge'
  get 'data_fix/result_details/:prg_key', to: 'data_fix#result_details', as: 'data_fix_result_details'

  # Explicit legacy routes (directly targeting DataFixLegacyController)
  get 'data_fix_legacy/review_sessions', to: 'data_fix_legacy#review_sessions', as: 'review_sessions_legacy'
  get 'data_fix_legacy/review_teams', to: 'data_fix_legacy#review_teams', as: 'review_teams_legacy'
  get 'data_fix_legacy/review_swimmers', to: 'data_fix_legacy#review_swimmers', as: 'review_swimmers_legacy'
  get 'data_fix_legacy/review_events', to: 'data_fix_legacy#review_events', as: 'review_events_legacy'
  get 'data_fix_legacy/review_results', to: 'data_fix_legacy#review_results', as: 'review_results_legacy'
  patch 'data_fix_legacy/update', to: 'data_fix_legacy#update', as: 'data_fix_update_legacy'
  get 'data_fix_legacy/coded_name', to: 'data_fix_legacy#coded_name', as: 'data_fix_coded_name_legacy'
  get 'data_fix_legacy/teams_for_swimmer/:swimmer_id', to: 'data_fix_legacy#teams_for_swimmer', as: 'data_fix_teams_for_swimmer_legacy'
  delete 'data_fix_legacy/purge', to: 'data_fix_legacy#purge', as: 'data_fix_purge_legacy'
  get 'data_fix_legacy/result_details/:prg_key', to: 'data_fix_legacy#result_details', as: 'data_fix_result_details_legacy'
  post 'data_fix_legacy/add_session', to: 'data_fix_legacy#add_session', as: 'data_fix_add_session_legacy'
  post 'data_fix_legacy/add_event', to: 'data_fix_legacy#add_event', as: 'data_fix_add_event_legacy'

  get 'push/index'
  post 'push/prepare'
  post 'push/upload'

  # Datagrid-actioned routes: (use prefix to avoid clashing w/ Engine resource routes)
  resources :api_badges, only: %i[index create update]
  delete 'api_badges', to: 'api_badges#destroy', as: 'api_badges_destroy'

  resources :api_calendars, only: %i[index create update]
  delete 'api_calendars', to: 'api_calendars#destroy', as: 'api_calendars_destroy'

  resources :api_categories, only: %i[index create update]
  delete 'api_categories', to: 'api_categories#destroy', as: 'api_categories_destroy'
  post 'api_categories/clone', to: 'api_categories#clone', as: 'api_categories_clone'

  resources :api_import_queues, only: %i[index create update]
  delete 'api_import_queues', to: 'api_import_queues#destroy', as: 'api_import_queues_destroy'

  resources :api_issues, only: %i[index create update]
  delete 'api_issues', to: 'api_issues#destroy', as: 'api_issues_destroy'
  get 'api_issues/check/:id', to: 'api_issues#check', as: 'api_issue_check'
  post 'api_issues/fix/:id', to: 'api_issues#fix', as: 'api_issue_fix'

  resources :api_meeting_reservations, only: %i[index create update]
  get 'api_meeting_reservations/expand', to: 'api_meeting_reservations#expand', as: 'api_meeting_reservations_expand'
  delete 'api_meeting_reservations', to: 'api_meeting_reservations#destroy', as: 'api_meeting_reservations_destroy'

  resources :api_meetings, only: %i[index update]
  get 'api_meetings/no_mirs', to: 'api_meetings#no_mirs', as: 'api_meetings_no_mirs'
  post 'api_meetings/clone', to: 'api_meetings#clone', as: 'api_meetings_clone'

  resources :api_seasons, only: %i[index create update]

  resources :api_standard_timings, only: %i[index create update]
  delete 'api_standard_timings', to: 'api_standard_timings#destroy', as: 'api_standard_timings_destroy'

  resources :api_swimmers, only: %i[index create update]
  resources :api_swimming_pools, only: %i[index create update]

  resources :api_team_affiliations, only: %i[index create update]
  delete 'api_team_affiliations', to: 'api_team_affiliations#destroy', as: 'api_team_affiliations_destroy'

  resources :api_team_managers, only: %i[index create update]
  delete 'api_team_managers', to: 'api_team_managers#destroy', as: 'api_team_managers_destroy'

  resources :api_teams, only: %i[index create update]

  resources :api_user_workshops, only: %i[index create update]
  delete 'api_user_workshops', to: 'api_user_workshops#destroy', as: 'api_user_workshops_destroy'

  resources :api_users, only: %i[index update]
  delete 'api_users', to: 'api_users#destroy', as: 'api_users_destroy'

  resources :settings, only: %i[index update]
  post 'settings/api_config', to: 'settings#api_config', as: 'settings_api_config'
  delete 'settings', to: 'settings#destroy', as: 'settings_destroy'

  resources :stats, only: %i[index update]
  delete 'stats', to: 'stats#destroy', as: 'stats_destroy'
  post 'stats/clear', to: 'stats#clear', as: 'stats_clear'
end

app/controllers/file_list_controller.rb
# frozen_string_literal: true

require 'csv'

# = FileListController
#
# Parent controller for handling and displaying file lists.
#
class FileListController < ApplicationController
  # [GET] List CSV calendar files (and allow individual actions on them).
  #
  def calendar_files
    @dirnames = Rails.root.glob('crawler/data/calendar.new/*')
                     .map { |name| name.to_s.split('crawler/').last }
                     .sort
    @curr_dir = nil # (Show all calendar files at once)
    @filter = '*.csv'
    @files = Rails.root.glob("crawler/data/calendar.new/**/#{@filter}").sort
  end

  # [GET] List JSON meeting result files (and allow individual actions on them).
  # [XHR PUT] Update just the list of result files (used after current directory selection)
  #
  # == Sets/Uses:
  # - @filter => performs file filtering (default: '*.json')
  # - @parent_folder => selects which parent folder (default: 'results.new')
  #
  # === Params:
  # - :filter => override for the same-named internal member
  # - :parent_folder => as above
  #
  # rubocop:disable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
  def result_files
    @filter ||= file_params[:filter] || '*.json'
    @parent_folder ||= file_params[:parent_folder] || 'results.new'
    @dirnames = Rails.root.glob("crawler/data/#{@parent_folder}/*")
                     .map { |name| name.to_s.split('crawler/').last }
                     .sort

    if request.xhr? && request.put? && file_params[:curr_dir].present?
      @curr_dir = file_params[:curr_dir]
      @files = Rails.root.glob("crawler/#{@curr_dir}/**/#{@filter}").sort
      render('file_table_update') && return

    elsif request.put?
      flash[:warning] = I18n.t('data_import.errors.invalid_request')
      redirect_to(root_path) && return
    end

    @curr_dir = @dirnames.first || "data/#{@parent_folder}/" # use default parent folder for empty dir lists
    @files = Rails.root.glob("crawler/#{@curr_dir}/**/#{@filter}").sort
  end
  # rubocop:enable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
  #-- -------------------------------------------------------------------------
  #++

  # [AJAX GET] Displays the file renaming modal.
  #
  # == Params:
  # - <tt>file_path</tt>: the path to the file to be renamed
  #
  def edit_name
    unless request.xhr? && file_params[:file_path].present?
      flash[:warning] = I18n.t('data_import.errors.invalid_request')
      redirect_to(root_path) && return
    end

    @file_path = file_params[:file_path]
  end

  # [AJAX PUT] Renames the file specified by the given <tt>file_path</tt> parameter.
  #
  # == Params:
  # - <tt>file_path</tt>: the path to the file to be deleted
  # - <tt>new_name</tt>: new filename
  #
  def file_rename
    unless request.xhr? && file_params[:file_path].present? && file_params[:new_name].present?
      flash.now[:warning] = I18n.t('data_import.errors.invalid_request')
      redirect_to(root_path) && return
    end

    FileUtils.mkdir_p(File.dirname(file_params[:new_name])) # Ensure existence of the destination path
    File.rename(file_params[:file_path], file_params[:new_name])
    prepare_file_and_dir_list
    render('file_table_update')
  end

  # [AJAX GET] Displays the file editing modal.
  #
  # == Params:
  # - <tt>file_path</tt>: the path to the file to be renamed
  #
  def edit_file
    unless request.xhr? && file_params[:file_path].present?
      flash[:warning] = I18n.t('data_import.errors.invalid_request')
      redirect_to(root_path) && return
    end

    @file_path = file_params[:file_path]
    @file_content = File.read(file_params[:file_path])
    # Currently unused: (using custom editors is too much work for now)
    # @parsed_json = JSON.parse(@file_content) if file_params[:file_path].end_with?('.json')
    # rescue StandardError
    #   flash[:error] = I18n.t('data_import.errors.invalid_file_content')
    #   redirect_to(root_path) && return
  end

  # [AJAX PUT] Updates the contents of the file specified by the given <tt>file_path</tt> parameter.
  #
  # == Params:
  # - <tt>file_path</tt>: the path to the file to be deleted
  # - <tt>new_content</tt>: new file contents
  #
  def file_edit
    unless request.xhr? && file_params[:file_path].present? && file_params[:new_content].present?
      flash.now[:warning] = I18n.t('data_import.errors.invalid_request')
      redirect_to(root_path) && return
    end

    File.write(file_params[:file_path], file_params[:new_content])
    prepare_file_and_dir_list
    render('file_table_update')
  end

  # [AJAX DELETE] Deletes the file specified by the given <tt>file_path</tt> parameter.
  #
  # WARNING: irreversible and quite dangerous!
  #
  # == Params:
  # - <tt>file_path</tt>: the path to the file to be deleted
  #
  def file_delete
    unless request.xhr? || file_params[:file_path].present?
      flash.now[:warning] = I18n.t('data_import.errors.invalid_request')
      redirect_to(root_path) && return
    end

    File.delete(file_params[:file_path])
    prepare_file_and_dir_list
    render('file_table_update')
  end

  private

  # Strong parameters checking for file-related actions.
  def file_params
    params.permit(:file_path, :curr_dir, :filter, :parent_folder, :new_name, :new_content)
  end

  # Prepares the current dir, the dir list and the file list members given the
  # current file_params.
  def prepare_file_and_dir_list(filter = nil)
    file_ext = File.extname(file_params[:file_path])
    @curr_dir = File.dirname(file_params[:file_path]).split('crawler/').last
    @parent_folder = file_params[:parent_folder]
    @dirnames = Rails.root.glob("crawler/#{@curr_dir}/../*")
                     .map { |name| name.to_s.split('crawler/').last }
                     .sort

    # Clear current folder if we're handling calendar files:
    @curr_dir = nil if file_ext == '.csv'
    # Filter file list based on current extension:
    filter ||= "*#{file_ext}"
    @files = Rails.root.glob("crawler/#{@curr_dir}/**/#{filter}").sort
  end
end

app/views/file_list/_file_modal.html.haml
.modal.fade{ id: 'file-actions-modal', 'aria-hidden' => 'true', role: 'dialog', tabindex: '-1',
             'aria-labelledby' => 'generic file actions modal' }
  .modal-dialog.modal-lg{ role: 'document' }
    - dest_path = rename ? pull_file_rename_path : pull_file_edit_path

    = form_tag(dest_path, id: 'frm-file-actions', method: :put, remote: true) do
      = hidden_field_tag('file_path', file_path)
      .modal-content
        .modal-header
          %h5.modal-title{ id: 'file-actions-modal-title' }
            = I18n.t('datagrid.edit_modal.edit_title')
          %button.close{ 'aria-label' => I18n.t('datagrid.edit_modal.close_btn'), 'data-dismiss' => 'modal' }
            %span{ 'aria-hidden' => 'true' } &times;

        .modal-body{ id: 'file-actions-modal-body' }
          .form-group.row-fluid
            - if rename
              = text_field_tag('new_name', file_path, class: 'form-control')

            - else
              = hidden_field_tag('file_path', file_path)
              = text_area_tag('new_content', file_content, class: 'form-control', rows: 15)

        .modal-footer
          %button.btn.btn-sm.btn-outline-secondary{ 'aria-label' => I18n.t('datagrid.edit_modal.close_btn'),
                                                    'data-dismiss' => 'modal', type: 'button' }
            = I18n.t('datagrid.edit_modal.close_btn')

          %button.btn.btn-sm.btn-outline-danger{ id: 'btn-submit-save', type: 'submit', method: :put,
                  'aria-label' => I18n.t('datagrid.edit_modal.save_btn'),
                  data: { confirm: I18n.t('datagrid.edit_modal.save_changes_msg') } }
            = I18n.t('datagrid.edit_modal.save_btn')

app/views/file_list/_file_table.html.haml
-# Detect feasibility of multi-push
- if files.present? && filter.present? && filter == '*.sql'
  .row-fluid
    .container
      .row.justify-content-left.ml-0.mb-2
        .btn-group.mx-1.my-0#push-all-btn
          = link_to(push_upload_path(file_path: File.join(curr_dir, '*.sql')), method: :post,
                                     class: 'btn btn-sm btn-outline-warning mb-1', data: { toggle: 'tooltip',
                                     title: t('data_import.push.btn_all_sql_files_tooltip'),
                                     confirm: t('data_import.push.btn_all_sql_files_confirm') }) do
            %span
              = t('data_import.push.btn_all_sql_files')
              %i.fa.fa-upload

.row-fluid
  .container
    - if curr_dir.present? && dirnames.present?
      = form_tag(update_result_files_path(filter: filter, parent_folder: parent_folder), id: 'frm-dir-filter',
                 method: :put, remote: true) do
        .row
          .col
            .form-group
              = select_tag('curr_dir', options_for_select(dirnames, curr_dir), class: 'form-control')
          .col-2
            .form-group
              = submit_tag('↩', id: 'btn-apply-dir-filter', class: 'btn btn-sm btn-primary pt-1 mt-1',
                           'aria-label' => 'select current directory', type: 'submit')

    %table.table.table-striped.table-hover.table-sm
      %thead
        %tr.bg-light-blue
          %th.text-center{ scope: 'col' }
            %i Bytes
          %th.text-center{ scope: 'col' }
            %i Filenames (#{files&.size})
          %th.text-center{ scope: 'col' }
            &nbsp;
      %tbody
        - files&.each do |full_pathname|
          - extname = File.extname(full_pathname)
          %tr
            %td.text-right
              = File.size(full_pathname)
            %td
              = File.basename(full_pathname)
            %td.text-left
              = link_to(pull_file_delete_path(file_path: full_pathname), method: :delete, remote: true,
                        class: 'btn btn-sm btn-outline-danger mb-1',
                        data: { toggle: 'tooltip', title: t('data_import.file.btn_delete_tooltip'),
                        confirm: t('data_import.file.confirm_delete') }) do
                %i.fa.fa-trash-o
              &nbsp;
              = link_to(pull_edit_name_path(file_path: full_pathname), remote: true,
                        class: 'btn btn-sm btn-outline-primary mb-1', data: { toggle: 'tooltip',
                        title: t('data_import.file.btn_rename_tooltip') }) do
                %i.fa.fa-text-width
              &nbsp;
              - if extname != '.pdf'
                = link_to(pull_edit_file_path(file_path: full_pathname), remote: true,
                          class: 'btn btn-sm btn-outline-success mb-1', data: { toggle: 'tooltip',
                          title: t('data_import.file.btn_edit_tooltip') }) do
                  %i.fa.fa-pencil-square-o

              - case extname
              - when '.csv'
                &nbsp;
                = link_to(process_calendar_file_path(file_path: full_pathname), method: :post,
                          class: 'btn btn-sm btn-outline-warning mb-1', data: { toggle: 'tooltip',
                          title: t('data_import.file.btn_process_csv_tooltip') }) do
                  %i.fa.fa-bolt
              - when '.json'
                &nbsp;
                = link_to(review_sessions_legacy_path(file_path: full_pathname), method: :get,
                          class: 'btn btn-sm btn-outline-warning mb-1', data: { toggle: 'tooltip',
                          title: t('data_import.file.btn_process_json_tooltip') }) do
                  %i.fa.fa-cogs
                &nbsp;
                = link_to(review_sessions_path(file_path: full_pathname, phase_v2: 1), method: :get,
                          class: 'btn btn-sm btn-outline-primary mb-1', data: { toggle: 'tooltip',
                          title: t('data_import.file.btn_process_json_v2_tooltip') }) do
                  %i.fa.fa-bolt
              - when '.pdf'
                &nbsp;
                = link_to(pdf_extract_txt_path(file_path: full_pathname), method: :get,
                          class: 'btn btn-sm btn-outline-warning mb-1', data: { toggle: 'tooltip',
                          title: t('data_import.file.btn_process_pdf_tooltip') }) do
                  %i.fa.fa-cogs
                - if File.exist?(full_pathname.to_s.gsub('.pdf', '.txt'))
                  &nbsp;
                  %small TXT✔
                - if File.exist?(full_pathname.to_s.gsub(parent_folder, 'results.new').gsub('.pdf', '.json'))
                  &nbsp;
                  %small JSON✔
              - when '.sql'
                &nbsp;
                = link_to(push_upload_path(file_path: full_pathname), method: :post,
                          class: 'btn btn-sm btn-outline-warning mb-1', data: { toggle: 'tooltip',
                          title: t('data_import.file.btn_process_sql_tooltip'),
                          confirm: t('data_import.file.confirm_push') }) do
                  %i.fa.fa-upload
- if files && files.empty?
  .row-fluid.my-4
    .text-center.py-4.noresults= I18n.t('datagrid.no_results')

#file-modal

app/views/file_list/edit_file.js.erb
document.querySelector('#flash-messages-container').innerHTML = "<%=
  escape_javascript(
    render(partial: 'goggles/flash_messages')
  )
%>";

document.querySelector('#file-modal').innerHTML = "<%=
  escape_javascript(
    render(
      partial: 'file_modal',
      locals: {
        file_path: @file_path,
        file_content: @file_content,
        parsed_json: @parsed_json,
        rename: false
      }
    )
  )
%>";
$('#file-actions-modal').modal();

app/views/file_list/edit_name.js.erb
document.querySelector('#flash-messages-container').innerHTML = "<%=
  escape_javascript(
    render(partial: 'goggles/flash_messages')
  )
%>";

document.querySelector('#file-modal').innerHTML = "<%=
  escape_javascript(
    render(
      partial: 'file_modal',
      locals: {
        file_path: @file_path,
        rename: true
      }
    )
  )
%>";
$('#file-actions-modal').modal();

app/views/file_list/file_table_update.js.erb
$('#file-actions-modal').modal('hide');
document.querySelector('#flash-messages-container').innerHTML = "<%=
  escape_javascript(
    render(partial: 'goggles/flash_messages')
  )
%>";

document.querySelector('#file-list').innerHTML = "<%=
  escape_javascript(
    render(
      partial: 'file_list/file_table',
      locals: { dirnames: @dirnames, curr_dir: @curr_dir, files: @files, parent_folder: @parent_folder, filter: @filter }
    )
  )
%>";

// Re-run the pop-over controller (unnamed) bound to the main body layout, so that
// pop-overs & modals reappear even after a partial page redraw:
this.Stimulus.controllers[0].connect();