config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'best50m_results/index'
  devise_for :users, class_name: 'GogglesDb::User',
                     controllers: {
                       sessions: 'users/sessions'
                     }
  root to: 'home#index'

  # Mounting and usage of the Engine:
  mount GogglesDb::Engine => '/'

  get 'home/index'
  get 'home/latest_updates'

  get 'best_results/best_50m', to: 'best_results#best_50m', as: 'best_50m_results'
  get 'best_results/best_50_and_100', to: 'best_results#best_50_and_100', as: 'best_50_and_100_results'
  get 'best_results/best_50_and_100_5y', to: 'best_results#best_50_and_100_5y', as: 'best_50_and_100_5y_results'
  get 'best_results/best_in_3y', to: 'best_results#best_in_3y', as: 'best_in_3y_results'
  get 'best_results/best_in_5y', to: 'best_results#best_in_5y', as: 'best_in_5y_results'
  get 'best_results/all_time_best', to: 'best_results#all_time_best', as: 'all_time_best_results'

  get 'pull/index'
  get 'pull/calendar_files'
  get 'pull/result_files'
  put 'pull/result_files', to: 'pull#result_files', as: 'update_result_files'

  post 'pull/run_crawler_api', to: 'pull#run_crawler_api', as: 'run_crawler_api'
  get 'pull/edit_name'
  get 'pull/edit_file'
  put 'pull/file_rename'
  put 'pull/file_edit'
  delete 'pull/file_delete'
  post 'pull/process_calendar_file', to: 'pull#process_calendar_file', as: 'process_calendar_file'

  get 'pdf/extract_txt', to: 'pdf#extract_txt', as: 'pdf_extract_txt'
  put 'pdf/scan'
  put 'pdf/log_contents'

  get 'data_fix/commit_phase6_report'
  get 'data_fix/review_sessions', to: 'data_fix#review_sessions', as: 'review_sessions'
  get 'data_fix/review_teams', to: 'data_fix#review_teams', as: 'review_teams'
  get 'data_fix/review_swimmers', to: 'data_fix#review_swimmers', as: 'review_swimmers'
  get 'data_fix/review_events', to: 'data_fix#review_events', as: 'review_events'
  get 'data_fix/review_results', to: 'data_fix#review_results', as: 'review_results'
  get 'data_fix/results_chunk_v2', to: 'data_fix#results_chunk_v2', as: 'results_chunk_v2'
  post 'data_fix/commit_phase6', to: 'data_fix#commit_phase6', as: 'commit_phase6'
  patch 'data_fix/update_phase1_meeting', to: 'data_fix#update_phase1_meeting', as: 'update_phase1_meeting'
  patch 'data_fix/update_phase1_session', to: 'data_fix#update_phase1_session', as: 'update_phase1_session'
  post 'data_fix/add_session', to: 'data_fix#add_session', as: 'data_fix_add_session'
  delete 'data_fix/delete_session', to: 'data_fix#delete_session', as: 'data_fix_delete_session'
  post 'data_fix/rescan_phase1_sessions', to: 'data_fix#rescan_phase1_sessions', as: 'rescan_phase1_sessions'
  patch 'data_fix/update_phase2_team', to: 'data_fix#update_phase2_team', as: 'update_phase2_team'
  post 'data_fix/add_team', to: 'data_fix#add_team', as: 'data_fix_add_team'
  delete 'data_fix/delete_team', to: 'data_fix#delete_team', as: 'data_fix_delete_team'
  patch 'data_fix/update_phase3_swimmer', to: 'data_fix#update_phase3_swimmer', as: 'update_phase3_swimmer'
  post 'data_fix/add_swimmer', to: 'data_fix#add_swimmer', as: 'data_fix_add_swimmer'
  delete 'data_fix/delete_swimmer', to: 'data_fix#delete_swimmer', as: 'data_fix_delete_swimmer'
  post 'data_fix/merge_phase3_swimmers', to: 'data_fix#merge_phase3_swimmers', as: 'merge_phase3_swimmers'
  patch 'data_fix/update_phase4_event', to: 'data_fix#update_phase4_event', as: 'update_phase4_event'
  post 'data_fix/add_event', to: 'data_fix#add_event', as: 'data_fix_add_event'
  delete 'data_fix/delete_event', to: 'data_fix#delete_event', as: 'data_fix_delete_event'
  patch 'data_fix/update', to: 'data_fix#update', as: 'data_fix_update'
  get 'data_fix/coded_name', to: 'data_fix#coded_name'
  get 'data_fix/teams_for_swimmer/:swimmer_id', to: 'data_fix#teams_for_swimmer', as: 'data_fix_teams_for_swimmer'
  delete 'data_fix/purge', to: 'data_fix#purge', as: 'data_fix_purge'
  get 'data_fix/result_details/:prg_key', to: 'data_fix#result_details', as: 'data_fix_result_details'

  # Explicit legacy routes (directly targeting DataFixLegacyController)
  get 'data_fix_legacy/review_sessions', to: 'data_fix_legacy#review_sessions', as: 'review_sessions_legacy'
  get 'data_fix_legacy/review_teams', to: 'data_fix_legacy#review_teams', as: 'review_teams_legacy'
  get 'data_fix_legacy/review_swimmers', to: 'data_fix_legacy#review_swimmers', as: 'review_swimmers_legacy'
  get 'data_fix_legacy/review_events', to: 'data_fix_legacy#review_events', as: 'review_events_legacy'
  get 'data_fix_legacy/review_results', to: 'data_fix_legacy#review_results', as: 'review_results_legacy'
  patch 'data_fix_legacy/update', to: 'data_fix_legacy#update', as: 'data_fix_update_legacy'
  get 'data_fix_legacy/coded_name', to: 'data_fix_legacy#coded_name', as: 'data_fix_coded_name_legacy'
  get 'data_fix_legacy/teams_for_swimmer/:swimmer_id', to: 'data_fix_legacy#teams_for_swimmer', as: 'data_fix_teams_for_swimmer_legacy'
  delete 'data_fix_legacy/purge', to: 'data_fix_legacy#purge', as: 'data_fix_purge_legacy'
  get 'data_fix_legacy/result_details/:prg_key', to: 'data_fix_legacy#result_details', as: 'data_fix_result_details_legacy'
  post 'data_fix_legacy/add_session', to: 'data_fix_legacy#add_session', as: 'data_fix_add_session_legacy'
  post 'data_fix_legacy/add_event', to: 'data_fix_legacy#add_event', as: 'data_fix_add_event_legacy'

  get 'push/index'
  post 'push/prepare'
  post 'push/upload'

  # Datagrid-actioned routes: (use prefix to avoid clashing w/ Engine resource routes)
  resources :api_badges, only: %i[index create update]
  delete 'api_badges', to: 'api_badges#destroy', as: 'api_badges_destroy'

  resources :api_calendars, only: %i[index create update]
  delete 'api_calendars', to: 'api_calendars#destroy', as: 'api_calendars_destroy'

  resources :api_categories, only: %i[index create update]
  delete 'api_categories', to: 'api_categories#destroy', as: 'api_categories_destroy'
  post 'api_categories/clone', to: 'api_categories#clone', as: 'api_categories_clone'

  resources :api_import_queues, only: %i[index create update]
  delete 'api_import_queues', to: 'api_import_queues#destroy', as: 'api_import_queues_destroy'

  resources :api_issues, only: %i[index create update]
  delete 'api_issues', to: 'api_issues#destroy', as: 'api_issues_destroy'
  get 'api_issues/check/:id', to: 'api_issues#check', as: 'api_issue_check'
  post 'api_issues/fix/:id', to: 'api_issues#fix', as: 'api_issue_fix'

  resources :api_meeting_reservations, only: %i[index create update]
  get 'api_meeting_reservations/expand', to: 'api_meeting_reservations#expand', as: 'api_meeting_reservations_expand'
  delete 'api_meeting_reservations', to: 'api_meeting_reservations#destroy', as: 'api_meeting_reservations_destroy'

  resources :api_meetings, only: %i[index update]
  get 'api_meetings/no_mirs', to: 'api_meetings#no_mirs', as: 'api_meetings_no_mirs'
  post 'api_meetings/clone', to: 'api_meetings#clone', as: 'api_meetings_clone'

  resources :api_seasons, only: %i[index create update]

  resources :api_standard_timings, only: %i[index create update]
  delete 'api_standard_timings', to: 'api_standard_timings#destroy', as: 'api_standard_timings_destroy'

  resources :api_swimmers, only: %i[index create update]
  resources :api_swimming_pools, only: %i[index create update]

  resources :api_team_affiliations, only: %i[index create update]
  delete 'api_team_affiliations', to: 'api_team_affiliations#destroy', as: 'api_team_affiliations_destroy'

  resources :api_team_managers, only: %i[index create update]
  delete 'api_team_managers', to: 'api_team_managers#destroy', as: 'api_team_managers_destroy'

  resources :api_teams, only: %i[index create update]

  resources :api_user_workshops, only: %i[index create update]
  delete 'api_user_workshops', to: 'api_user_workshops#destroy', as: 'api_user_workshops_destroy'

  resources :api_users, only: %i[index update]
  delete 'api_users', to: 'api_users#destroy', as: 'api_users_destroy'

  resources :settings, only: %i[index update]
  post 'settings/api_config', to: 'settings#api_config', as: 'settings_api_config'
  delete 'settings', to: 'settings#destroy', as: 'settings_destroy'

  resources :stats, only: %i[index update]
  delete 'stats', to: 'stats#destroy', as: 'stats_destroy'
  post 'stats/clear', to: 'stats#clear', as: 'stats_clear'
end

app/views/data_fix_legacy/_data_fix_header.html.haml
.row
  .col-1.text-center.mt-2
    = link_to(pull_result_files_path, method: :get,
              data: { toggle: 'tooltip', title: 'Go back to result file list' }) do
      %i.btn.btn-sm.btn-primary.fa.fa-chevron-circle-left
  .col
    .container.bg-light-blue.py-2.shadow-box#file-name-box
      .row-fluid.text-center
        %h5
          = file_path.split('data/').last
      - if retry_needed
        .row-fluid.text-center
          %b.text-danger.animated.infinite.flash= t('data_import.data_fix.msg.warning_retry_needed')

app/views/data_fix_legacy/_data_fix_tabs.html.haml
.row-fluid.text-center.pb-3.my-2
  %ul.nav.nav-tabs
    %li.nav-item
      - active = active_tab == 'sessions'
      - if active
        .nav-link.active
          1: Meeting & Session
          = link_to(review_sessions_legacy_path(reparse: true, file_path: file_path), method: :get,
                    data: { toggle: 'tooltip',
                    title: t('data_import.file.btn_reparse_json_tooltip') }) do
            %i.btn.btn-sm.btn-outline-warning.fa.fa-refresh
      - else
        %a.nav-link{ href: review_sessions_legacy_path(file_path: file_path),
                     onclick: "$('#loading-indicator').removeClass('d-none');" }
          1: Meeting & Session

    %li.nav-item
      - active = active_tab == 'teams'
      - if active
        .nav-link.active
          2: Teams
          = link_to(review_teams_legacy_path(reparse: true, file_path: file_path), method: :get,
                    data: { toggle: 'tooltip',
                    title: t('data_import.file.btn_reparse_json_tooltip') }) do
            %i.btn.btn-sm.btn-outline-warning.fa.fa-refresh
      - else
        %a.nav-link{ href: review_teams_legacy_path(file_path: file_path),
                     onclick: "$('#loading-indicator').removeClass('d-none');" }
          2: Teams

    %li.nav-item
      - active = active_tab == 'swimmers'
      - if active
        .nav-link.active
          3: Swimmers
          = link_to(review_swimmers_legacy_path(reparse: true, file_path: file_path), method: :get,
                    data: { toggle: 'tooltip',
                    title: t('data_import.file.btn_reparse_json_tooltip') }) do
            %i.btn.btn-sm.btn-outline-warning.fa.fa-refresh
      - else
        %a.nav-link{ href: review_swimmers_legacy_path(file_path: file_path),
                     onclick: "$('#loading-indicator').removeClass('d-none');" }
          3: Swimmers

    %li.nav-item
      - active = active_tab == 'events'
      - if active
        .nav-link.active
          4: Events
          = link_to(review_events_legacy_path(reparse: true, file_path: file_path), method: :get,
                    data: { toggle: 'tooltip',
                    title: t('data_import.file.btn_reparse_json_tooltip') }) do
            %i.btn.btn-sm.btn-outline-warning.fa.fa-refresh
      - else
        %a.nav-link{ href: review_events_legacy_path(file_path: file_path),
                     onclick: "$('#loading-indicator').removeClass('d-none');" }
          4: Events

    %li.nav-item
      - active = active_tab == 'results'
      - if active
        .nav-link.active
          5: Results
          = link_to(review_results_legacy_path(reparse: true, file_path: file_path), method: :get,
                    data: { toggle: 'tooltip',
                    title: t('data_import.file.btn_reparse_json_tooltip') }) do
            %i.btn.btn-sm.btn-outline-warning.fa.fa-refresh
      - else
        %a.nav-link{ href: review_results_legacy_path(file_path: file_path),
                     onclick: "$('#loading-indicator').removeClass('d-none');" }
          5: Results

app/views/data_fix_legacy/_modal_progress.html.haml
.modal#modal-progress{ 'aria-hidden': 'true', 'aria-labelledby': 'modal-progress',
                       role: 'dialog', tabindex: '-1' }
  .modal-dialog.modal-dialog-centered.modal-lg
    .modal-content
      .m-2#progress-msg
        Loading...
      .progress
        .progress-bar#di-progress{ role: 'progressbar', 'aria-valuenow': '0',
                                   'aria-valuemin': '0', 'aria-valuemax': '100',
                                   style: 'width: 0%', data: { value: 0, total: 100 } } 0%

app/views/data_fix_legacy/_swimmer_form.html.haml
:ruby
  # "Subkey" is the actual swimmer key (with spaces) translated to to a node ID (with underscores)
  # (it's needed to reference the DOM IDs from the AutoCompleteComponent)
  subkey_for_dom_id = swimmer_key.gsub(/[\s`'^?&%$!"<>:;,.*àèéìòù]/, '_')
  src_dom = "#swimmer_#{subkey_for_dom_id}_id"
  target_dom = "#swimmer_#{subkey_for_dom_id}_swimmer_id"
  onchange_event = "$('#{target_dom}').val($('#{src_dom}').val()); $('#{target_dom}').trigger('change')"
  gender_type_opts = options_from_collection_for_select(GogglesDb::GenderType.all, 'id', 'label',
                                                        swimmer&.gender_type_id)

= form_for(swimmer, url: data_fix_update_legacy_path(swimmer, model: 'swimmer'), method: :patch) do |f|
  = hidden_field_tag('key', swimmer_key) # actual entity key, used to retrieve the entity from data hash
  = hidden_field_tag('dom_valid_key', subkey_for_dom_id) # valid DOM ID key using inside the form
  = hidden_field_tag('file_path', file_path)
  .container
    .form-group
      .field
        = label_tag("swimmer[#{subkey_for_dom_id}][id]", 'fuzzy matches')
        / ORIG.: (Needs updated SwimmerDecorator [DB] handling nil for gender_type)
        -# = select_tag("swimmer[#{subkey_for_dom_id}][id]", options_from_collection_for_select(swimmer_matches || [],
        -#              'id', 'display_label', swimmer&.id), include_blank: true, class: 'form-control',
        -#              onchange: onchange_event)
        - select_options_for_swimmer = (swimmer_matches || []).map { |sw| [sw.id, "#{sw.complete_name} (#{sw.gender_type&.label}, #{sw.year_of_birth}#{sw.year_guessed ? '~' : ''})"] }
        = select_tag("swimmer[#{subkey_for_dom_id}][id]", options_for_select(select_options_for_swimmer), include_blank: true, class: 'form-control',
                     onchange: onchange_event)
    .row
      .col-auto
        = render(AutoCompleteComponent.new(show_top_labels: true,
                base_dom_id: "swimmer[#{subkey_for_dom_id}]", base_api_url: api_url,
                default_value: swimmer&.id,
                detail_endpoint: 'swimmer', base_name: 'swimmer', label_column: 'complete_name',
                search_endpoint: 'swimmers', search_column: 'complete_name',
                search2_dom_id: "swimmer_#{subkey_for_dom_id}_year_of_birth", search2_column: 'year_of_birth',
                target3_dom_id: "swimmer_#{subkey_for_dom_id}_gender_type_id", target3_column: 'gender_type_id',
                target4_dom_id: "swimmer_#{subkey_for_dom_id}_last_name", target4_column: 'last_name',
                target5_dom_id: "swimmer_#{subkey_for_dom_id}_first_name", target5_column: 'first_name',
                target6_dom_id: "swimmer_#{subkey_for_dom_id}_complete_name", target6_column: 'complete_name',
                jwt: current_user.jwt))
      .col-lg-3.col-md-5.col-sm-6.my-1
        .form-group
          .field
            = label_tag("swimmer[#{subkey_for_dom_id}][last_name]", 'last_name')
            = text_field_tag("swimmer[#{subkey_for_dom_id}][last_name]", swimmer&.last_name&.upcase,
                              class: 'form-control', required: true, placeholder: 'last_name')
      .col-lg-3.col-md-5.col-sm-6.my-1
        .form-group
          .field
            = label_tag("swimmer[#{subkey_for_dom_id}][first_name]", 'first_name')
            = text_field_tag("swimmer[#{subkey_for_dom_id}][first_name]", swimmer&.first_name&.upcase,
                              class: 'form-control', required: true, placeholder: 'first_name')

      .col-lg-6.col-md-6.my-2
        .form-group
          .field
            = label_tag("swimmer[#{subkey_for_dom_id}][complete_name]", 'complete_name')
            = text_field_tag("swimmer[#{subkey_for_dom_id}][complete_name]", swimmer&.complete_name&.upcase,
                              class: 'form-control', required: true, placeholder: 'complete_name')
      .col-lg-2.col-md-3.col-sm-4.my-2
        = label_tag("swimmer[#{subkey_for_dom_id}][year_of_birth]", 'year_of_birth')
        = number_field_tag("swimmer[#{subkey_for_dom_id}][year_of_birth]", swimmer&.year_of_birth, min: 1910,
                            max: Time.zone.today.year, required: true, autofocus: true, class: 'form-control')
      .col-lg-2.col-md-3.col-sm-4.my-2
        = label_tag("swimmer[#{subkey_for_dom_id}][gender_type_id]", 'gender_type')
        = select_tag("swimmer[#{subkey_for_dom_id}][gender_type_id]", gender_type_opts, class: 'form-control')

    .form-group
      = f.submit(t('data_import.generic_save_btn'), id: 'btn-save-session', class: 'btn btn-primary',
                 'aria-label': 'Save', type: 'submit',
                 data: { confirm: t('data_import.btn_save_confirm') })

app/views/data_fix_legacy/_team_form.html.haml
:ruby
  # "Subkey" is the actual team key (with spaces) translated to a node name to a node ID (with underscores)
  # (it's needed to reference the DOM IDs from the AutoCompleteComponent)
  subkey_for_dom_id = team_key.gsub(/[\s`'^?&%$!"<>:;,.*àèéìòù]/, '_')
  src_dom = "#team_#{subkey_for_dom_id}_id"
  target_dom = "#team_#{subkey_for_dom_id}_team_id"
  onchange_event = "$('#{target_dom}').val($('#{src_dom}').val()); $('#{target_dom}').trigger('change')"

= form_for(team, url: data_fix_update_legacy_path(team, model: 'team'), method: :patch) do |f|
  = hidden_field_tag('key', team_key) # actual entity key, used to retrieve the entity from data hash
  = hidden_field_tag('dom_valid_key', subkey_for_dom_id) # valid DOM ID key using inside the form
  = hidden_field_tag('file_path', file_path)
  .container
    .form-group
      .field
        = label_tag("team[#{subkey_for_dom_id}][id]", 'fuzzy matches')
        = select_tag("team[#{subkey_for_dom_id}][id]", options_from_collection_for_select(team_matches || [], 'id',
                     'display_label', team&.id), include_blank: true, class: 'form-control', onchange: onchange_event)
    .row
      .col-6
        = render(AutoCompleteComponent.new(show_top_labels: true,
                base_dom_id: "team[#{subkey_for_dom_id}]", base_api_url: api_url,
                detail_endpoint: 'team', base_name: 'team', label_column: 'editable_name',
                default_value: team&.id,
                search_endpoint: 'teams', search_column: 'name',
                target3_dom_id: "team_#{subkey_for_dom_id}_editable_name", target3_column: 'editable_name',
                target4_dom_id: "team_#{subkey_for_dom_id}_city_id", target4_column: 'city_id',
                target5_dom_id: "team_#{subkey_for_dom_id}_name", target5_column: 'name',
                target6_dom_id: "team_#{subkey_for_dom_id}_name_variations", target6_column: 'name_variations',
                jwt: current_user.jwt))
      .col-lg-4.col-md-6
        .form-group
          .field
            = label_tag("team[#{subkey_for_dom_id}][editable_name]", 'editable_name')
            = text_field_tag("team[#{subkey_for_dom_id}][editable_name]", team&.editable_name,
                              class: 'form-control', required: true, placeholder: 'editable_name')
    .row
      .col-5
        .form-group
          .field
            = label_tag("team[#{subkey_for_dom_id}][name]", 'name')
            = text_field_tag("team[#{subkey_for_dom_id}][name]", team&.name,
                              class: 'form-control', required: true, placeholder: 'name')
      .col-7
        .form-group
          .field
            = label_tag("team[#{subkey_for_dom_id}][name_variations]", 'name_variations')
            = text_field_tag("team[#{subkey_for_dom_id}][name_variations]", team&.name_variations,
                              class: 'form-control', placeholder: 'name_variations')

    = render(AutoCompleteComponent.new(show_top_labels: true,
            base_dom_id: "team[#{subkey_for_dom_id}]", base_api_url: api_url,
            default_value: team&.city_id,
            detail_endpoint: 'city', base_name: 'city', label_column: 'area',
            search_endpoint: 'cities', search_column: 'name',
            target2_field: 'area', target2_column: 'area',
            target2_class: 'offset-lg-2 offset-md-3 offset-sm-3 col-md-4 col-sm-4 my-1',
            jwt: current_user.jwt))

    .form-group
      = f.submit(t('data_import.generic_save_btn'), id: 'btn-save-session', class: 'btn btn-primary',
                 'aria-label': 'Save', type: 'submit',
                 data: { confirm: t('data_import.btn_save_confirm') })

app/views/data_fix_legacy/review_sessions.html.haml
-# haml-lint:disable ViewLength
-# haml-lint:disable LineLength
= render(partial: 'modal_progress')
.wrapper-body
  .main-content
    %section.my-2#title-box
      = render(partial: 'data_fix_header', locals: { file_path: @file_path, retry_needed: @retry_needed })
    %section.my-2#review-sessions-tabs
      = render(partial: 'data_fix_tabs', locals: { active_tab: 'sessions', file_path: @file_path })

    %section.my-2#review-sessions
      .container-fluid
        .row-fluid
          #meeting-card
            .card
              .row-fluid.p-1#meeting-header{ class: @meeting.id.present? ? 'bg-light' : 'bg-light-yellow' }
                %h5.mb-0
                  %button.btn.btn-link{ id: 'edit-meeting', data: { target: '#meeting-panel', toggle: 'collapse',
                                        'aria-expanded' => 'false', 'aria-controls' => 'edit-meeting' } }
                    %b= @meeting.description
                    &nbsp;
                    - if @meeting.id.present?
                      ID: #{@meeting.id}
                      = @meeting.valid? ? '✅' : '🔵'
                    - else
                      🆕
              .row-fluid.p-1
                .bg-light-grey
                  %small
                    %i.text-muted
                      %pre
                        🔑 #{@data_hash['name']},&nbsp;
                        #{@data_hash['dateDay1']} #{@data_hash['dateMonth1']} #{@data_hash['dateYear1']}
                        &nbsp; ... &nbsp;
                        #{@data_hash['dateDay2']} #{@data_hash['dateMonth2']} #{@data_hash['dateYear2']}
              .collapse#meeting-panel{ 'aria-labelledby' => 'meeting-header', 'data-parent' => '#meeting-card' }
                .card-body.border-bottom.border-secondary
                  = render(partial: 'meeting_form',
                           locals: { api_url: @api_url, meeting_entity: @meeting_entity,
                                     file_path: @file_path })
        .row.mt-4
          - if @data_hash['manifestURL'].present? || @data_hash['resultsPdfURL'].present?
            - if @data_hash['manifestURL'].present?
              .col-auto
                = link_to(@data_hash['manifestURL']) do
                  .btn.btn-sm.btn-outline-primary
                    %i.fa.fa-download
                    = t('data_import.data_fix.link_to_manifest_download')
            - if @data_hash['resultsPdfURL'].present?
              .col-auto
                = link_to(@data_hash['resultsPdfURL']) do
                  .btn.btn-sm.btn-outline-primary
                    %i.fa.fa-download
                    = t('data_import.data_fix.link_to_results_pdf_download')
          .col-auto
            = link_to(review_sessions_legacy_path(reparse: 'sessions', file_path: @file_path),
                      method: :get, data: { toggle: 'tooltip',
                                            title: t('data_import.data_fix.btn_reparse_session_tooltip') }) do
              .btn.btn-sm.btn-warning
                %i.fa.fa-refresh
                = t('data_import.data_fix.btn_reparse_session_label')

          .col-auto
            = form_tag(data_fix_add_session_legacy_path, id: 'frm-add-session', method: :post) do
              = hidden_field_tag('file_path', @file_path)
              = label_tag('use_default_pool_key', t('data_import.data_fix.add_session_with_shared_place'))
              = check_box_tag('use_default_pool_key', false)
              %button.btn.btn-sm.btn-outline-success#btn-add-session{ type: 'submit',
                  method: :delete, 'aria-label' => 'Add session',
                  data: { confirm: t('data_import.data_fix.confirm_add_session'),
                          disable_with: t('home.please_wait') } }
                %i.fa.fa-plus
                = t('data_import.data_fix.btn_add_session')

        .row-fluid.mt-4
          %p.text-center
            %i= t('data_import.data_fix.notice_for_add_session')
          - @meeting_sessions.each_with_index do |meeting_session, index|
            - pool_type_opts = options_from_collection_for_select(GogglesDb::PoolType.all, 'id', 'long_label',
                                 @swimming_pools[index]&.pool_type_id || cookies[:pool_type_id])
            %div{ id: "meeting-session-card-#{index}",
                  class: meeting_session&.id.present? ? 'bg-light' : 'bg-light-yellow' }
              .card.mt-2
                .row-fluid.p-1{ id: "meeting-session-header-#{index}",
                                class: @meeting.id.present? ? 'bg-light' : 'bg-light-yellow' }
                  %h5.row.align-items-center.mb-0
                    .col-auto
                      %button.btn.btn-link{ id: "edit-meeting-session-#{index}",
                                            data: { target: "#meeting-session-panel-#{index}",
                                            toggle: 'collapse', 'aria-expanded' => 'false',
                                            'aria-controls' => 'edit-meeting-session' } }
                        = meeting_session&.description
                    .col-auto
                      - if meeting_session&.id.present?
                        ID: #{meeting_session&.id}
                        = meeting_session.valid? ? '✅' : '🔵'
                      - else
                        🆕
                    / Don't show the purge button for already-serialized sessions (with ID)
                    - if meeting_session&.id.blank?
                      .col-auto
                        = form_tag(data_fix_purge_legacy_path(meeting_session, model: 'meeting_session'), id: "frm-purge-session-#{index}", method: :delete) do
                          = hidden_field_tag('key', index) # actual entity key, used to retrieve the entity from data hash
                          = hidden_field_tag('file_path', @file_path)
                          %button.btn.btn-sm.btn-outline-danger{ id: "btn-purge-#{index}", type: 'submit', method: :delete,
                              'aria-label' => 'Purge',
                              data: { confirm: t('data_import.data_fix.confirm_purge', key: index),
                              disable_with: t('home.please_wait') } }
                            %i.fa.fa-trash-o
                .collapse{ id: "meeting-session-panel-#{index}", 'aria-labelledby' => "meeting-session-header-#{index}",
                           'data-parent' => "#meeting-session-card-#{index}" }
                  .card-body.border-bottom.border-secondary
                    = render(partial: 'meeting_session_form', locals: { meeting_session: meeting_session,
                             index: index, swimming_pool: @swimming_pools[index], pool_type_opts: pool_type_opts,
                             city: @cities[index], city_key: @city_keys[index],
                             api_url: @api_url, data_hash: @data_hash, file_path: @file_path })

app/views/data_fix_legacy/teams_for_swimmer.js.erb
document.querySelector("#team-list-for-<%= @swimmer_id %>")
        .innerHTML = "<%= escape_javascript(@team_names) %>";