config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'best50m_results/index'
  devise_for :users, class_name: 'GogglesDb::User',
                     controllers: {
                       sessions: 'users/sessions'
                     }
  root to: 'home#index'

  # Mounting and usage of the Engine:
  mount GogglesDb::Engine => '/'

  get 'home/index'
  get 'home/latest_updates'

  get 'best_results/best_50m', to: 'best_results#best_50m', as: 'best_50m_results'
  get 'best_results/best_50_and_100', to: 'best_results#best_50_and_100', as: 'best_50_and_100_results'
  get 'best_results/best_50_and_100_5y', to: 'best_results#best_50_and_100_5y', as: 'best_50_and_100_5y_results'
  get 'best_results/best_in_3y', to: 'best_results#best_in_3y', as: 'best_in_3y_results'
  get 'best_results/best_in_5y', to: 'best_results#best_in_5y', as: 'best_in_5y_results'
  get 'best_results/all_time_best', to: 'best_results#all_time_best', as: 'all_time_best_results'

  get 'pull/index'
  get 'pull/calendar_files'
  get 'pull/result_files'
  put 'pull/result_files', to: 'pull#result_files', as: 'update_result_files'

  post 'pull/run_crawler_api', to: 'pull#run_crawler_api', as: 'run_crawler_api'
  get 'pull/edit_name'
  get 'pull/edit_file'
  put 'pull/file_rename'
  put 'pull/file_edit'
  delete 'pull/file_delete'
  post 'pull/process_calendar_file', to: 'pull#process_calendar_file', as: 'process_calendar_file'

  get 'pdf/extract_txt', to: 'pdf#extract_txt', as: 'pdf_extract_txt'
  put 'pdf/scan'
  put 'pdf/log_contents'

  get 'data_fix/commit_phase6_report'
  get 'data_fix/review_sessions', to: 'data_fix#review_sessions', as: 'review_sessions'
  get 'data_fix/review_teams', to: 'data_fix#review_teams', as: 'review_teams'
  get 'data_fix/review_swimmers', to: 'data_fix#review_swimmers', as: 'review_swimmers'
  get 'data_fix/review_events', to: 'data_fix#review_events', as: 'review_events'
  get 'data_fix/review_results', to: 'data_fix#review_results', as: 'review_results'
  get 'data_fix/results_chunk_v2', to: 'data_fix#results_chunk_v2', as: 'results_chunk_v2'
  post 'data_fix/commit_phase6', to: 'data_fix#commit_phase6', as: 'commit_phase6'
  patch 'data_fix/update_phase1_meeting', to: 'data_fix#update_phase1_meeting', as: 'update_phase1_meeting'
  patch 'data_fix/update_phase1_session', to: 'data_fix#update_phase1_session', as: 'update_phase1_session'
  post 'data_fix/add_session', to: 'data_fix#add_session', as: 'data_fix_add_session'
  delete 'data_fix/delete_session', to: 'data_fix#delete_session', as: 'data_fix_delete_session'
  post 'data_fix/rescan_phase1_sessions', to: 'data_fix#rescan_phase1_sessions', as: 'rescan_phase1_sessions'
  patch 'data_fix/update_phase2_team', to: 'data_fix#update_phase2_team', as: 'update_phase2_team'
  post 'data_fix/add_team', to: 'data_fix#add_team', as: 'data_fix_add_team'
  delete 'data_fix/delete_team', to: 'data_fix#delete_team', as: 'data_fix_delete_team'
  patch 'data_fix/update_phase3_swimmer', to: 'data_fix#update_phase3_swimmer', as: 'update_phase3_swimmer'
  post 'data_fix/add_swimmer', to: 'data_fix#add_swimmer', as: 'data_fix_add_swimmer'
  delete 'data_fix/delete_swimmer', to: 'data_fix#delete_swimmer', as: 'data_fix_delete_swimmer'
  post 'data_fix/merge_phase3_swimmers', to: 'data_fix#merge_phase3_swimmers', as: 'merge_phase3_swimmers'
  patch 'data_fix/update_phase4_event', to: 'data_fix#update_phase4_event', as: 'update_phase4_event'
  post 'data_fix/add_event', to: 'data_fix#add_event', as: 'data_fix_add_event'
  delete 'data_fix/delete_event', to: 'data_fix#delete_event', as: 'data_fix_delete_event'
  patch 'data_fix/update', to: 'data_fix#update', as: 'data_fix_update'
  get 'data_fix/coded_name', to: 'data_fix#coded_name'
  get 'data_fix/teams_for_swimmer/:swimmer_id', to: 'data_fix#teams_for_swimmer', as: 'data_fix_teams_for_swimmer'
  delete 'data_fix/purge', to: 'data_fix#purge', as: 'data_fix_purge'
  get 'data_fix/result_details/:prg_key', to: 'data_fix#result_details', as: 'data_fix_result_details'

  # Explicit legacy routes (directly targeting DataFixLegacyController)
  get 'data_fix_legacy/review_sessions', to: 'data_fix_legacy#review_sessions', as: 'review_sessions_legacy'
  get 'data_fix_legacy/review_teams', to: 'data_fix_legacy#review_teams', as: 'review_teams_legacy'
  get 'data_fix_legacy/review_swimmers', to: 'data_fix_legacy#review_swimmers', as: 'review_swimmers_legacy'
  get 'data_fix_legacy/review_events', to: 'data_fix_legacy#review_events', as: 'review_events_legacy'
  get 'data_fix_legacy/review_results', to: 'data_fix_legacy#review_results', as: 'review_results_legacy'
  patch 'data_fix_legacy/update', to: 'data_fix_legacy#update', as: 'data_fix_update_legacy'
  get 'data_fix_legacy/coded_name', to: 'data_fix_legacy#coded_name', as: 'data_fix_coded_name_legacy'
  get 'data_fix_legacy/teams_for_swimmer/:swimmer_id', to: 'data_fix_legacy#teams_for_swimmer', as: 'data_fix_teams_for_swimmer_legacy'
  delete 'data_fix_legacy/purge', to: 'data_fix_legacy#purge', as: 'data_fix_purge_legacy'
  get 'data_fix_legacy/result_details/:prg_key', to: 'data_fix_legacy#result_details', as: 'data_fix_result_details_legacy'
  post 'data_fix_legacy/add_session', to: 'data_fix_legacy#add_session', as: 'data_fix_add_session_legacy'
  post 'data_fix_legacy/add_event', to: 'data_fix_legacy#add_event', as: 'data_fix_add_event_legacy'

  get 'push/index'
  post 'push/prepare'
  post 'push/upload'

  # Datagrid-actioned routes: (use prefix to avoid clashing w/ Engine resource routes)
  resources :api_badges, only: %i[index create update]
  delete 'api_badges', to: 'api_badges#destroy', as: 'api_badges_destroy'

  resources :api_calendars, only: %i[index create update]
  delete 'api_calendars', to: 'api_calendars#destroy', as: 'api_calendars_destroy'

  resources :api_categories, only: %i[index create update]
  delete 'api_categories', to: 'api_categories#destroy', as: 'api_categories_destroy'
  post 'api_categories/clone', to: 'api_categories#clone', as: 'api_categories_clone'

  resources :api_import_queues, only: %i[index create update]
  delete 'api_import_queues', to: 'api_import_queues#destroy', as: 'api_import_queues_destroy'

  resources :api_issues, only: %i[index create update]
  delete 'api_issues', to: 'api_issues#destroy', as: 'api_issues_destroy'
  get 'api_issues/check/:id', to: 'api_issues#check', as: 'api_issue_check'
  post 'api_issues/fix/:id', to: 'api_issues#fix', as: 'api_issue_fix'

  resources :api_meeting_reservations, only: %i[index create update]
  get 'api_meeting_reservations/expand', to: 'api_meeting_reservations#expand', as: 'api_meeting_reservations_expand'
  delete 'api_meeting_reservations', to: 'api_meeting_reservations#destroy', as: 'api_meeting_reservations_destroy'

  resources :api_meetings, only: %i[index update]
  get 'api_meetings/no_mirs', to: 'api_meetings#no_mirs', as: 'api_meetings_no_mirs'
  post 'api_meetings/clone', to: 'api_meetings#clone', as: 'api_meetings_clone'

  resources :api_seasons, only: %i[index create update]

  resources :api_standard_timings, only: %i[index create update]
  delete 'api_standard_timings', to: 'api_standard_timings#destroy', as: 'api_standard_timings_destroy'

  resources :api_swimmers, only: %i[index create update]
  resources :api_swimming_pools, only: %i[index create update]

  resources :api_team_affiliations, only: %i[index create update]
  delete 'api_team_affiliations', to: 'api_team_affiliations#destroy', as: 'api_team_affiliations_destroy'

  resources :api_team_managers, only: %i[index create update]
  delete 'api_team_managers', to: 'api_team_managers#destroy', as: 'api_team_managers_destroy'

  resources :api_teams, only: %i[index create update]

  resources :api_user_workshops, only: %i[index create update]
  delete 'api_user_workshops', to: 'api_user_workshops#destroy', as: 'api_user_workshops_destroy'

  resources :api_users, only: %i[index update]
  delete 'api_users', to: 'api_users#destroy', as: 'api_users_destroy'

  resources :settings, only: %i[index update]
  post 'settings/api_config', to: 'settings#api_config', as: 'settings_api_config'
  delete 'settings', to: 'settings#destroy', as: 'settings_destroy'

  resources :stats, only: %i[index update]
  delete 'stats', to: 'stats#destroy', as: 'stats_destroy'
  post 'stats/clear', to: 'stats#clear', as: 'stats_clear'
end

app/helpers/pull_helper.rb
# frozen_string_literal: true

# = PullHelper
#
module PullHelper
  # (unused at the moment)
end

app/views/pull/_crawler_status_box.html.haml
.container.bg-light-green.pt-2.shadow-box#crawler-status-box
  .row-fluid.text-center
    %h5
      🕷 Crawler Server
  .row
    .col-12
      %em
        localhost:7000
      %i.fa.fa-spin.fa-question-circle-o#crawler-status-icon
      &nbsp;
      %b
        %small.text-secondary#crawler-status= t('data_import.errors.crawler_connecting')
  .row
    .col-12.pb-2
      %small#crawler-detail
        = t('data_import.errors.crawler_connecting')
  .row-fluid.pb-2.d-none#crawler-progress-row
    .progress
      .progress-bar#crawler-progress{ role: 'progressbar', 'aria-valuenow': '0',
                                      'aria-valuemin': '0', 'aria-valuemax': '100',
                                      style: 'width: 0%' } 20%

app/views/pull/_crawler_tabs.html.haml
.row-fluid.text-center.pb-3.my-2
  %ul.nav.nav-tabs
    %li.nav-item
      - active = active_tab == 'crawler'
      %a.nav-link{ href: active ? '#' : pull_index_path, class: active ? 'active' : nil }
        = t('data_import.calendar.crawler_status_page_title')
    %li.nav-item
      - active = active_tab == 'calendar'
      %a.nav-link{ href: active ? '#' : pull_calendar_files_path, class: active ? 'active' : nil }
        = t('data_import.calendar.calendar_files_page_title')
    %li.nav-item
      - active = active_tab == 'pdfs'
      %a.nav-link{ href: active ? '#' : pull_result_files_path(filter: '*.pdf', parent_folder: 'pdfs'),
                   class: active ? 'active' : nil }
        = t('data_import.calendar.pdfs_page_title')
    %li.nav-item
      - active = active_tab == 'results'
      %a.nav-link{ href: active ? '#' : pull_result_files_path, class: active ? 'active' : nil }
        = t('data_import.calendar.result_files_page_title')

app/views/pull/_file_table.html.haml
.row-fluid
  .container
    - if curr_dir.present? && dirnames.present?
      = form_tag(update_result_files_path, id: 'frm-dir-filter', method: :put, remote: true) do
        .row
          .col
            .form-group
              = select_tag('curr_dir', options_for_select(dirnames, curr_dir), class: 'form-control')
          .col-2
            .form-group
              = submit_tag('↩', id: 'btn-apply-dir-filter', class: 'btn btn-sm btn-primary pt-1 mt-1',
                           'aria-label' => 'select current directory', type: 'submit')

    %table.table.table-striped.table-hover.table-sm
      %thead
        %tr.bg-light-blue
          %th.text-center{ scope: 'col' }
            %i Bytes
          %th.text-center{ scope: 'col' }
            %i Filenames (#{files&.size})
          %th.text-center{ scope: 'col' }
            &nbsp;
      %tbody
        - files&.each do |full_pathname|
          %tr
            %td.text-right
              = File.size(full_pathname)
            %td
              = File.basename(full_pathname)
            %td.text-center
              = link_to(pull_file_delete_path(file_path: full_pathname), method: :delete, remote: true,
                        class: 'btn btn-sm btn-outline-danger mb-1',
                        data: { toggle: 'tooltip', title: t('data_import.file.btn_delete_tooltip'),
                        confirm: t('data_import.file.confirm_delete') }) do
                %i.fa.fa-trash-o
              &nbsp;
              = link_to(pull_edit_name_path(file_path: full_pathname), remote: true,
                        class: 'btn btn-sm btn-outline-primary mb-1', data: { toggle: 'tooltip',
                        title: t('data_import.file.btn_rename_tooltip') }) do
                %i.fa.fa-text-width
              &nbsp;
              = link_to(pull_edit_file_path(file_path: full_pathname), remote: true,
                        class: 'btn btn-sm btn-outline-success mb-1', data: { toggle: 'tooltip',
                        title: t('data_import.file.btn_edit_tooltip') }) do
                %i.fa.fa-pencil-square-o
              - case File.extname(full_pathname)
              - when '.csv'
                &nbsp;
                = link_to(process_calendar_file_path(file_path: full_pathname), method: :post,
                          class: 'btn btn-sm btn-outline-warning mb-1', data: { toggle: 'tooltip',
                          title: t('data_import.file.btn_process_csv_tooltip') }) do
                  %i.fa.fa-bolt
              - when '.json'
                &nbsp;
                = link_to(prepare_result_file_path(file_path: full_pathname), method: :post,
                          class: 'btn btn-sm btn-outline-warning mb-1', data: { toggle: 'tooltip',
                          title: t('data_import.file.btn_process_json_tooltip') }) do
                  %i.fa.fa-cogs

#file-modal

app/views/pull/calendar_files.html.haml
.wrapper-body
  .main-content
    %section.my-2#status-box
      = render(partial: 'crawler_status_box')

    %section.my-2#crawler-tabs
      = render(partial: 'crawler_tabs', locals: { active_tab: 'calendar' })

    %section#file-list
      = render(partial: 'file_list/file_table', locals: { dirnames: @dirnames, curr_dir: @curr_dir,
               files: @files, parent_folder: @parent_folder, filter: @filter })

app/views/pull/file_table_update.js.erb
$('#file-actions-modal').modal('hide');
document.querySelector('#flash-messages-container').innerHTML = "<%=
  escape_javascript(
    render(partial: 'goggles/flash_messages')
  )
%>";

document.querySelector('#file-list').innerHTML = "<%=
  escape_javascript(
    render(
      partial: 'file_table',
      locals: { dirnames: @dirnames, curr_dir: @curr_dir, files: @files }
    )
  )
%>";

app/views/pull/index.html.haml
.wrapper-body
  .main-content
    %section.my-2#status-box
      = render(partial: 'crawler_status_box')

    %section.my-2#crawler-tabs
      = render(partial: 'crawler_tabs', locals: { active_tab: 'crawler' })

    %section.my-2#calendar-crawl
      .container.pt-3.shadow-box#curr-config-box
        = form_tag(run_crawler_api_path, id: 'frm-run-crawler', method: :post) do
          #crawler-accordion.accordion
            .card.mb-2#calendar-crawler-box
              .card-header#calendar-header
                %h5.mb-0
                  %button.btn.btn-link{'data-toggle' => 'collapse', 'data-target' => '#calendar-collapse',
                                       'aria-expanded' => 'true', 'aria-controls' => 'calendar-collapse',
                                       type: 'button'}
                    = t('data_import.crawler_headers.calendar')
              #calendar-collapse.collapse.show{'aria-labelledby' => 'calendar-header', 'data-parent' => '#crawler-accordion'}
                .card-body
                  .row-fluid
                    %i.text-secondary Target Season (ID 242, 252, ...)
                  .row
                    .col-9
                      = render(AutoCompleteComponent.new(show_top_labels: true, base_name: 'season',
                               search_column: 'season_label',
                               target2_field: 'year_text', target2_column: 'year_text', target2_class: 'col-auto my-1',
                               label_column: 'description',
                               payload: @season_list))
                    .col
                      .form-group
                        .field
                          = label_tag('sub_menu_type', t('data_import.config.sub_menu_type'))
                          -# Left non-localized as these are the actual target labels on the sub-menu items:
                          = select_tag('sub_menu_type', options_for_select(['Eventi', 'Riepilogo Eventi', 'Archivio 2012-']),
                                      class: 'form-control')
            .card.mb-2#results-crawler-box
              .card-header#results-header
                %h5.mb-0
                  %button.btn.btn-link.collapsed{'data-toggle' => 'collapse', 'data-target' => '#results-collapse', 'aria-expanded' => 'false', 'aria-controls' => 'results-collapse', type: 'button'}
                    = t('data_import.crawler_headers.results')
              #results-collapse.collapse{'aria-labelledby' => 'results-header', 'data-parent' => '#crawler-accordion'}
                .card-body
                  .row-fluid
                    %i.text-secondary Target Layout (ID 4, 5, ...; ID 0 = calendar auto-detect) + URL
                  .row.my-4
                    .col-5
                      = render(AutoCompleteComponent.new(show_top_labels: true, base_name: 'layout',
                              search_column: 'label', label_column: 'label',
                              target4_dom_id: 'target_url', target4_column: 'base_url',
                              payload: @url_base_list))
                    .col-7
                      .form-group
                        .field
                          = label_tag('target_url', t('data_import.config.target_url'))
                          = text_field_tag('target_url', nil, class: 'form-control')
                      .row-fluid
                        %small
                          %i.form-text.text-muted (<a href="https://www.federnuoto.it/home/master.html">FIN Master</a>,&nbsp; <a href="https://microplus.it/events/">Microplus events</a>)
                    .offset-5.col-7
                      .form-group
                        .field
                          = label_tag('target_event', t('data_import.config.target_event'))
                          = text_field_tag('target_event', nil, class: 'form-control')
          .row
            .col-6.mt-2.mb-3.text-left
              = submit_tag(t('data_import.calendar.btn_run_crawler'), id: 'btn-run-calendar-crawler',
                           class: 'btn btn-sm btn-outline-primary', 'aria-label' => 'run calendar crawler',
                           type: 'submit', data: { confirm: t('data_import.calendar.btn_run_crawler_confirm') })
            .col-6.mt-2.mb-3.text-right
              = link_to('#', id: 'btn-clear-log',
                        class: 'btn btn-sm btn-outline-danger', 'aria-label' => 'clear log',
                        onclick: '$("#crawler_log").html(""); return false;',
                        data: { confirm: t('data_import.calendar.btn_clear_log_confirm') }) do
                %i.fa.fa-trash-o
                &nbsp;
                = t('data_import.calendar.btn_clear_log')
        .row
          .col-12.pb-3
            = text_area_tag(:crawler_log, nil, rows: 15, autofocus: true, class: 'form-control form-control-sm',
                            'aria-describedby' => 'calendar crawl log')

app/views/pull/result_files.html.haml
.wrapper-body
  .main-content
    %section.my-2#status-box
      = render(partial: 'crawler_status_box')

    %section.my-2#crawler-tabs
      = render(partial: 'crawler_tabs', locals: { active_tab: @parent_folder == 'pdfs' ? 'pdfs' : 'results' })

    %section#file-list
      = render(partial: 'file_list/file_table', locals: { dirnames: @dirnames, curr_dir: @curr_dir,
               files: @files, parent_folder: @parent_folder, filter: @filter })