config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'best50m_results/index'
  devise_for :users, class_name: 'GogglesDb::User',
                     controllers: {
                       sessions: 'users/sessions'
                     }
  root to: 'home#index'

  # Mounting and usage of the Engine:
  mount GogglesDb::Engine => '/'

  get 'home/index'
  get 'home/latest_updates'

  get 'best_results/best_50m', to: 'best_results#best_50m', as: 'best_50m_results'
  get 'best_results/best_50_and_100', to: 'best_results#best_50_and_100', as: 'best_50_and_100_results'
  get 'best_results/best_50_and_100_5y', to: 'best_results#best_50_and_100_5y', as: 'best_50_and_100_5y_results'
  get 'best_results/best_in_3y', to: 'best_results#best_in_3y', as: 'best_in_3y_results'
  get 'best_results/best_in_5y', to: 'best_results#best_in_5y', as: 'best_in_5y_results'
  get 'best_results/all_time_best', to: 'best_results#all_time_best', as: 'all_time_best_results'

  get 'pull/index'
  get 'pull/calendar_files'
  get 'pull/result_files'
  put 'pull/result_files', to: 'pull#result_files', as: 'update_result_files'

  post 'pull/run_crawler_api', to: 'pull#run_crawler_api', as: 'run_crawler_api'
  get 'pull/edit_name'
  get 'pull/edit_file'
  put 'pull/file_rename'
  put 'pull/file_edit'
  delete 'pull/file_delete'
  post 'pull/process_calendar_file', to: 'pull#process_calendar_file', as: 'process_calendar_file'

  get 'pdf/extract_txt', to: 'pdf#extract_txt', as: 'pdf_extract_txt'
  put 'pdf/scan'
  put 'pdf/log_contents'

  get 'data_fix/commit_phase6_report'
  get 'data_fix/review_sessions', to: 'data_fix#review_sessions', as: 'review_sessions'
  get 'data_fix/review_teams', to: 'data_fix#review_teams', as: 'review_teams'
  get 'data_fix/review_swimmers', to: 'data_fix#review_swimmers', as: 'review_swimmers'
  get 'data_fix/review_events', to: 'data_fix#review_events', as: 'review_events'
  get 'data_fix/review_results', to: 'data_fix#review_results', as: 'review_results'
  get 'data_fix/results_chunk_v2', to: 'data_fix#results_chunk_v2', as: 'results_chunk_v2'
  post 'data_fix/commit_phase6', to: 'data_fix#commit_phase6', as: 'commit_phase6'
  patch 'data_fix/update_phase1_meeting', to: 'data_fix#update_phase1_meeting', as: 'update_phase1_meeting'
  patch 'data_fix/update_phase1_session', to: 'data_fix#update_phase1_session', as: 'update_phase1_session'
  post 'data_fix/add_session', to: 'data_fix#add_session', as: 'data_fix_add_session'
  delete 'data_fix/delete_session', to: 'data_fix#delete_session', as: 'data_fix_delete_session'
  post 'data_fix/rescan_phase1_sessions', to: 'data_fix#rescan_phase1_sessions', as: 'rescan_phase1_sessions'
  patch 'data_fix/update_phase2_team', to: 'data_fix#update_phase2_team', as: 'update_phase2_team'
  post 'data_fix/add_team', to: 'data_fix#add_team', as: 'data_fix_add_team'
  delete 'data_fix/delete_team', to: 'data_fix#delete_team', as: 'data_fix_delete_team'
  patch 'data_fix/update_phase3_swimmer', to: 'data_fix#update_phase3_swimmer', as: 'update_phase3_swimmer'
  post 'data_fix/add_swimmer', to: 'data_fix#add_swimmer', as: 'data_fix_add_swimmer'
  delete 'data_fix/delete_swimmer', to: 'data_fix#delete_swimmer', as: 'data_fix_delete_swimmer'
  post 'data_fix/merge_phase3_swimmers', to: 'data_fix#merge_phase3_swimmers', as: 'merge_phase3_swimmers'
  patch 'data_fix/update_phase4_event', to: 'data_fix#update_phase4_event', as: 'update_phase4_event'
  post 'data_fix/add_event', to: 'data_fix#add_event', as: 'data_fix_add_event'
  delete 'data_fix/delete_event', to: 'data_fix#delete_event', as: 'data_fix_delete_event'
  patch 'data_fix/update', to: 'data_fix#update', as: 'data_fix_update'
  get 'data_fix/coded_name', to: 'data_fix#coded_name'
  get 'data_fix/teams_for_swimmer/:swimmer_id', to: 'data_fix#teams_for_swimmer', as: 'data_fix_teams_for_swimmer'
  delete 'data_fix/purge', to: 'data_fix#purge', as: 'data_fix_purge'
  get 'data_fix/result_details/:prg_key', to: 'data_fix#result_details', as: 'data_fix_result_details'

  # Explicit legacy routes (directly targeting DataFixLegacyController)
  get 'data_fix_legacy/review_sessions', to: 'data_fix_legacy#review_sessions', as: 'review_sessions_legacy'
  get 'data_fix_legacy/review_teams', to: 'data_fix_legacy#review_teams', as: 'review_teams_legacy'
  get 'data_fix_legacy/review_swimmers', to: 'data_fix_legacy#review_swimmers', as: 'review_swimmers_legacy'
  get 'data_fix_legacy/review_events', to: 'data_fix_legacy#review_events', as: 'review_events_legacy'
  get 'data_fix_legacy/review_results', to: 'data_fix_legacy#review_results', as: 'review_results_legacy'
  patch 'data_fix_legacy/update', to: 'data_fix_legacy#update', as: 'data_fix_update_legacy'
  get 'data_fix_legacy/coded_name', to: 'data_fix_legacy#coded_name', as: 'data_fix_coded_name_legacy'
  get 'data_fix_legacy/teams_for_swimmer/:swimmer_id', to: 'data_fix_legacy#teams_for_swimmer', as: 'data_fix_teams_for_swimmer_legacy'
  delete 'data_fix_legacy/purge', to: 'data_fix_legacy#purge', as: 'data_fix_purge_legacy'
  get 'data_fix_legacy/result_details/:prg_key', to: 'data_fix_legacy#result_details', as: 'data_fix_result_details_legacy'
  post 'data_fix_legacy/add_session', to: 'data_fix_legacy#add_session', as: 'data_fix_add_session_legacy'
  post 'data_fix_legacy/add_event', to: 'data_fix_legacy#add_event', as: 'data_fix_add_event_legacy'

  get 'push/index'
  post 'push/prepare'
  post 'push/upload'

  # Datagrid-actioned routes: (use prefix to avoid clashing w/ Engine resource routes)
  resources :api_badges, only: %i[index create update]
  delete 'api_badges', to: 'api_badges#destroy', as: 'api_badges_destroy'

  resources :api_calendars, only: %i[index create update]
  delete 'api_calendars', to: 'api_calendars#destroy', as: 'api_calendars_destroy'

  resources :api_categories, only: %i[index create update]
  delete 'api_categories', to: 'api_categories#destroy', as: 'api_categories_destroy'
  post 'api_categories/clone', to: 'api_categories#clone', as: 'api_categories_clone'

  resources :api_import_queues, only: %i[index create update]
  delete 'api_import_queues', to: 'api_import_queues#destroy', as: 'api_import_queues_destroy'

  resources :api_issues, only: %i[index create update]
  delete 'api_issues', to: 'api_issues#destroy', as: 'api_issues_destroy'
  get 'api_issues/check/:id', to: 'api_issues#check', as: 'api_issue_check'
  post 'api_issues/fix/:id', to: 'api_issues#fix', as: 'api_issue_fix'

  resources :api_meeting_reservations, only: %i[index create update]
  get 'api_meeting_reservations/expand', to: 'api_meeting_reservations#expand', as: 'api_meeting_reservations_expand'
  delete 'api_meeting_reservations', to: 'api_meeting_reservations#destroy', as: 'api_meeting_reservations_destroy'

  resources :api_meetings, only: %i[index update]
  get 'api_meetings/no_mirs', to: 'api_meetings#no_mirs', as: 'api_meetings_no_mirs'
  post 'api_meetings/clone', to: 'api_meetings#clone', as: 'api_meetings_clone'

  resources :api_seasons, only: %i[index create update]

  resources :api_standard_timings, only: %i[index create update]
  delete 'api_standard_timings', to: 'api_standard_timings#destroy', as: 'api_standard_timings_destroy'

  resources :api_swimmers, only: %i[index create update]
  resources :api_swimming_pools, only: %i[index create update]

  resources :api_team_affiliations, only: %i[index create update]
  delete 'api_team_affiliations', to: 'api_team_affiliations#destroy', as: 'api_team_affiliations_destroy'

  resources :api_team_managers, only: %i[index create update]
  delete 'api_team_managers', to: 'api_team_managers#destroy', as: 'api_team_managers_destroy'

  resources :api_teams, only: %i[index create update]

  resources :api_user_workshops, only: %i[index create update]
  delete 'api_user_workshops', to: 'api_user_workshops#destroy', as: 'api_user_workshops_destroy'

  resources :api_users, only: %i[index update]
  delete 'api_users', to: 'api_users#destroy', as: 'api_users_destroy'

  resources :settings, only: %i[index update]
  post 'settings/api_config', to: 'settings#api_config', as: 'settings_api_config'
  delete 'settings', to: 'settings#destroy', as: 'settings_destroy'

  resources :stats, only: %i[index update]
  delete 'stats', to: 'stats#destroy', as: 'stats_destroy'
  post 'stats/clear', to: 'stats#clear', as: 'stats_clear'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

require 'version'

# = HomeController
#
# Main landing actions.
#
class HomeController < ApplicationController
  # [GET] Main landing page default action.
  #
  # Computes also main counters displayed on the landing dashboard.
  #
  def index
    @users_count = count_remote_rows_for('users')
    @iqs_count = count_remote_rows_for('import_queues')
    @issues_count = count_remote_rows_for('issues')
    @api_uses_count = count_remote_rows_for('api_daily_uses')
  end

  # [GET] Retrieve the latest updates from both production & staging servers endpoints
  # (regardless of the currently connected server according to the settings).
  # If the API is down and returns an error, the corresponding section will be empty and
  # the error will be signaled.
  #
  def latest_updates
    # (ASSUMES: 447 => production, 446 => staging)
    @prod_updates = request_latest_updates(447)
    if @prod_updates.key?('error')
      flash[:error] = I18n.t('dashboard.api_proxy_error', error_code: @prod_updates['error'].split.last, error_msg: @prod_updates['error'])
      @prod_updates = {}
    end

    @staging_updates = request_latest_updates(446)
    return unless @staging_updates.key?('error')

    flash[:error] = I18n.t('dashboard.api_proxy_error', error_code: @staging_updates['error'].split.last, error_msg: @staging_updates['error'])
    @staging_updates = {}
  end

  private

  # Retrieves the remote row total for a specified endpoint.
  def count_remote_rows_for(api_endpoint)
    result = APIProxy.call(method: :get, url: api_endpoint, jwt: current_user&.jwt)
    result.headers[:total] || 0
  end

  # Retrieves the hash containing the latest row updates for the specified server (distinguished by the
  # port used for the API endpoint); nil in case of error.
  def request_latest_updates(port_override)
    result = APIProxy.call(method: :get, url: 'tools/latest_updates', jwt: current_user.jwt, port_override: port_override)
    result.body.present? && result.body.exclude?('DOCTYPE HTML') ? JSON.parse(result.body) : { 'error' => "Error #{result.code}" }
  end
end

app/views/home/_data_import.html.haml
.mb-4.mx-1
  .col-12
    .card.text-dark.bg-light-blue.h-100
      .card-body
        .rotate
          %i.fa.fa-database.fa-4x
        %h6.text-uppercase
          %span
            Data-import
            %sup
              %i.fa.fa-question-circle{ data: { toggle: 'tooltip', title: t('dashboard.data_import_helper') } }
        .row.mb-3
          .col.py-2
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: pull_index_path }
              %i.fa.fa-download
              PULL data (crawler)
          .offset-lg-0.col-lg-4.offset-md-1.col-md-5.offset-sm-0.col-sm-6.py-2
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: pull_result_files_path }
              %i.fa.fa-edit
              DATA-FIX results
          .col.py-2
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: push_index_path }
              %i.fa.fa-upload
              PUSH data
        .row-fluid.mb-3
          = link_to(home_latest_updates_path, class: 'btn btn-outline-primary',
                    'data-turbolinks' => 'false') do
            %i.fa.fa-search
            Fetch Latest updates...

app/views/home/_manage_entities.html.haml
.mb-4.mx-1
  .col-12
    .card.text-dark.bg-light-blue.h-100
      .card-body
        .rotate
          %i.fa.fa-cogs.fa-4x
        %h6.text-uppercase
          = t('dashboard.manage_entities')
          %sup
            %i.fa.fa-question-circle{ data: { toggle: 'tooltip', title: t('dashboard.manage_entities_help') } }
        .row.mb-3
          .offset-lg-0.col-lg-4.offset-md-1.col-md-5.offset-sm-0.col-sm-6.py-2
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_teams_path }
              = t('dashboard.teams.title')
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_team_affiliations_path }
              = t('dashboard.team_affiliations.title')
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_team_managers_path }
              = t('dashboard.team_managers.title')
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_meeting_reservations_path }
              = t('dashboard.meeting_reservations.title')
          .offset-lg-0.col-lg-4.offset-md-1.col-md-5.offset-sm-0.col-sm-6.py-2
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_seasons_path }
              = t('dashboard.seasons.title')
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_categories_path }
              = t('dashboard.categories.title')
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_meetings_path }
              Meetings
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_user_workshops_path }
              = t('dashboard.user_workshops.title')
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_standard_timings_path }
              = t('dashboard.standard_timings.title')
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_calendars_path }
              = t('dashboard.calendars.title')
          .offset-lg-0.col-lg-4.offset-md-1.col-md-5.offset-sm-0.col-sm-6.py-2
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_swimmers_path }
              = t('dashboard.swimmers.title')
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_badges_path }
              = t('dashboard.badges.title')
            %a.btn.btn-lg.btn-outline-primary.my-1{ href: api_swimming_pools_path }
              = t('dashboard.swimming_pools.title')
            %a.btn.btn-lg.btn-outline-primary.disabled.my-1{ href: '#' }
              Ind. results (MIR)
            %a.btn.btn-lg.btn-outline-primary.disabled.my-1{ href: '#' }
              User results (UR)
            %a.btn.btn-lg.btn-outline-primary.disabled.my-1{ href: '#' }
              Relay results (MRR)
          .offset-lg-0.col-lg-4.offset-md-1.col-md-5.offset-sm-0.col-sm-6.py-2
            %a.btn.btn-lg.btn-outline-primary.disabled.my-1{ href: '#' }
              Laps
            %a.btn.btn-lg.btn-outline-primary.disabled.my-1{ href: '#' }
              User Laps
            %a.btn.btn-lg.btn-outline-primary.disabled.my-1{ href: '#' }
              Relay Laps (& Swimmers)

app/views/home/_tools.haml
.mb-4.mx-1
  .col-12
    .card.text-dark.bg-light-blue.h-100
      .card-body
        .rotate
          %i.fa.fa-cogs.fa-4x
        %h6.text-uppercase
          Tools
          %sup
            %i.fa.fa-question-circle{ data: { toggle: 'tooltip', title: t('dashboard.tools_helper') } }
        .row.mb-3
          .col.py-2
            %a.btn.btn-sm.btn-outline-primary.py-2{ href: best_50m_results_path }
              %i.fa.fa-search
              = t('best_results.best_50m.button_label')
          .col.py-2
            %a.btn.btn-sm.btn-outline-primary.py-2{ href: best_50_and_100_results_path }
              %i.fa.fa-search
              = t('best_results.best_50_and_100.button_label')
          .col.py-2
            %a.btn.btn-sm.btn-outline-primary.py-2{ href: best_50_and_100_5y_results_path }
              %i.fa.fa-search
              = t('best_results.best_50_and_100_5y.button_label')
          .col.py-2
            %a.btn.btn-sm.btn-outline-primary.py-2{ href: best_in_3y_results_path }
              %i.fa.fa-search
              = t('best_results.best_in_3y.button_label')
          .col.py-2
            %a.btn.btn-sm.btn-outline-primary.py-2{ href: best_in_5y_results_path }
              %i.fa.fa-search
              = t('best_results.best_in_5y.button_label')
          .col.py-2
            %a.btn.btn-sm.btn-outline-primary.py-2{ href: all_time_best_results_path }
              %i.fa.fa-search
              = t('best_results.all_time_best.button_label')

app/views/home/_top_header.html.haml
.row-fluid.text-center
  %h5
    - api_url = GogglesDb::AppParameter.config.settings(:framework_urls).api
    🖥 API Server: #{api_url}
    - if api_url.ends_with?('446')
      %span.animated.infinite.flash.bg-success STAGING
    - elsif api_url.ends_with?('447')
      %span.animated.infinite.flash.bg-danger PRODUCTION
    - else
      %span.animated.infinite.flash.bg-warning UNKNOWN

    &nbsp;
    %a.btn.btn-sm.btn-outline-secondary{ href: settings_path }
      %i.fa.fa-cog

.row.mb-3.mx-1
  .offset-lg-0.col-lg-3.offset-md-1.col-md-5.offset-sm-0.col-sm-6.py-2
    %a.btn.card.text-white.bg-info.h-100{ href: stats_path }
      .card-body.bg-info
        .rotate
          %i.fa.fa-line-chart.fa-4x
        %h6.text-uppercase= t('dashboard.stats.title')
        %h1.display-4= api_uses_count

  .offset-lg-0.col-lg-3.offset-md-1.col-md-5.offset-sm-0.col-sm-6.py-2
    %a.btn.card.text-white.bg-warning.h-100{ href: api_import_queues_path }
      .card-body.bg-warning
        .rotate
          %i.fa.fa-list.fa-4x
        %h6.text-uppercase= t('dashboard.import_queues.title')
        %h1.display-4= iqs_count

  .offset-lg-0.col-lg-3.offset-md-1.col-md-5.offset-sm-0.col-sm-6.py-2
    %a.btn.card.text-white.bg-danger.h-100{ href: api_issues_path }
      .card-body.bg-danger
        .rotate
          %i.fa.fa-list.fa-4x
        %h6.text-uppercase= t('dashboard.issues.title')
        %h1.display-4= issues_count

  .offset-lg-0.col-lg-3.offset-md-1.col-md-5.offset-sm-0.col-sm-6.py-2
    %a.btn.card.bg-success.text-white.h-100{ href: api_users_path }
      .card-body.bg-success
        .rotate
          %i.fa.fa-user.fa-4x
        %h6.text-uppercase= t('dashboard.users.title')
        %h1.display-4= users_count

app/views/home/index.html.haml
.wrapper-body
  .spacer-left

  .main-content
    = render(partial: 'top_header', locals: { api_uses_count: @api_uses_count,
             iqs_count: @iqs_count, issues_count: @issues_count, users_count: @users_count })
    = render(partial: 'data_import')
    = render(partial: 'tools')
    = render(partial: 'manage_entities')

    %section.fixed-bottom#footer
      = render(Footer::MainComponent.new)

  .spacer-right

app/views/home/latest_updates.haml
.wrapper-body
  .spacer-left

  - prod_keys = @prod_updates.keys
  .main-content
    %table.table-sm.table-hover
      %thead
        %tr
          %th.text-center.border-0
            %b PRODUCTION
          %th.text-center.border-0
            %b STAGING
          %tbody
            / Focus on looping just on production keys & values:
            - prod_keys.each do |table_name|
              %tr
                %td.bg-light-blue.text-center.py-2{ colspan: 2 }
                  %b
                    %samp= table_name
              - prod_rows = @prod_updates.fetch(table_name, [])
              - staging_rows = @staging_updates.fetch(table_name, [])
              - (0...prod_rows.count).each do |idx|
                %tr
                  %td
                    - if prod_rows.present?
                      = HashRowDecorator.decorate(prod_rows[idx]).html_row
                    - else
                      &nbsp;-&nbsp;
                  %td
                    - if staging_rows.present?
                      = HashRowDecorator.decorate(staging_rows[idx]).html_row
                    - else
                      &nbsp;-&nbsp;
    .row.mb-3
      &nbsp;

  .spacer-right